checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    excluded_paths:
        - tests/*
build:
    environment:
        python: 3.8
    dependencies:
        before:
            - pip install poetry
            - poetry config virtualenvs.create false && poetry install
    tests:
        override:
            -
                command: 'tox -e 38'
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'
