language: python
dist: xenial
sudo: yes
python:
  - "3.8"
addons:
install:
  - pip install poetry
  - poetry config virtualenvs.create false && poetry install
script:
  - tox
after_success:
  - coveralls
