language: python
dist: xenial
sudo: yes
python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "pypy3.6-7.0.0"
addons:
install:
  - pip install poetry
  - poetry config virtualenvs.create false && poetry install
script:
  - python3.6 --version && tox -e 36
  - python3.7 --version && tox -e 37
  - python3.8 --version && tox -e 38
after_success:
  - coveralls
