language: python
dist: xenial
sudo: yes
python:
  - "3.8"
install:
  - pip install poetry
  - poetry config virtualenvs.create false && poetry install
script:
  - tox -e 38
after_success:
  - coveralls
